### ISSUE TITLE
Speed-up SNB with Multi-call

### ISSUE THREAD

**Issue by sergiy-skalelabs** [skalenetwork/IMA#1467]
**SKALE Network Browser** part of **IMA Agent** does a lot of read-only `eth_call`-s. These calls can be optimized by packing them into multi-calls using already deployed contract known as `Multicall3` and corresponding interaction components:
- https://wagmi.sh/core/actions/multicall
- https://www.npmjs.com/package/ethereum-multicall

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/IMA/issues/1413
- [ ] https://github.com/skalenetwork/internal-support/issues/569
- [ ] https://github.com/skalenetwork/IMA/issues/1531
```

**Comment by sergiy-skalelabs** [comment]
See PR here https://github.com/skalenetwork/IMA/pull/1452

**Comment by DmytroNazarenko** [comment]
[2.0.0-beta.0](https://github.com/skalenetwork/IMA/releases/tag/2.0.0-beta.0)

**Comment by EvgeniyZZ** [comment]
Verified: not working at all 
2023-09-19 17:17:19.124: Will start parallel IMA transfer loops in main thread 0...
2023-09-19 17:19:16.640: Failed to start parallel periodic SNB refresh in main thread 0, error is: timeout of 120 reached, will restart periodic SNB refresh in non-parallel mode
2023-09-19 17:19:16.640: main thread 0 will inform worker thread to stop periodic SNB refresh...


[imaParallelB13.txt](https://github.com/skalenetwork/IMA/files/12664775/imaParallelB13.txt)

**Comment by DmytroNazarenko** [comment]
IMA: 2.0.0-beta.15

**Comment by EvgeniyZZ** [comment]
Add log output:  
Process started 
Process finished

**Comment by EvgeniyZZ** [comment]
Can't to verify speed up improvements.
