### ISSUE TITLE
IMA: getPastEvents sometimes work significantly slow as expected

### ISSUE THREAD

**Issue by EvgeniyZZ** [skalenetwork/IMA#1620]
**Description** 
Case: compatibility check 
IMA version 11/16: 2.0.0
IMA version 5/16: 1.5.0-beta.1
Skaled: the same for all - 3.16.1

**Step to reproduce**
Run transfers loop between schain
When processing message takes more than 60 seconds observe logs on working node

**Actual result** 
In some regular use case search of IMA msg can takes more then 30-... min, depends on amount of blocks on the schain. 
NOTE: Root cause investigate in progress 

**Expected result** 
IMA processing msg should not takes more than 40 seconds in average. getPastEvents should parse logs not longer than 5-7 seconds based on previous results, and results on nodes not affected by this problem.

NOTE: Look closer on logs, attention to PWA thread  on affected chain. 
Compare imaGPE_big.txt with imaIterativeScan13.txt and imaIterativeScan12.txt

[imaGPE_big.txt](https://github.com/skalenetwork/IMA/files/13022989/imaGPE_big.txt)
[imaGPE.txt](https://github.com/skalenetwork/IMA/files/13022986/imaGPE.txt)
[imaIterativeScan12.txt](https://github.com/skalenetwork/IMA/files/13022987/imaIterativeScan12.txt)
[imaIS12.txt](https://github.com/skalenetwork/IMA/files/13022988/imaIS12.txt)
[imaIterativeScan13.txt](https://github.com/skalenetwork/IMA/files/13022983/imaIterativeScan13.txt)
[imaGPE13.txt](https://github.com/skalenetwork/IMA/files/13022984/imaGPE13.txt)

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/IMA/issues/1554
- [ ] https://github.com/skalenetwork/IMA/issues/1554
```

```[tasklist]
### Tasks
- [ ] https://github.com/skalenetwork/IMA/issues/1554
```

**Comment by EvgeniyZZ** [comment]
Verified: Can't reproduce. 
IMA Agent: 2.0.1
