### ISSUE TITLE
Implement IMA Execution Manager

### ISSUE THREAD

**Issue by PolinaKiporenko** [skalenetwork/IMA#1700]
### Problem

SKALE Network is a Multichain network which is already allow users to interact between SKALE chains(on one chain then on another), but not providing execution on another chains with default tokens bridged from Ethereum.
To be able to customize execution between chains developers need to create their own TokenManager-compatible contracts and connect them to IMA which is not so scalable and do not allow seamless operations with valuable assets(ERC20, NFT) which can cause to token fragmentation or need to be more controlled via liquidity based model bridges or similar.

Example (1): User A has X USDC on Nebula chain and want to buy NFT for X USDC on NFT Marketplace on Calypso chain.

### Solution

Add ability to send messages to the different receiver and execute arbitrary data on receiver side only on SKALE chain side.

SKALE Engineering team has already implemented similar solutions in Marionette and IMA contracts. 

Where IMA base layer (MessageProxy contracts) executing messages in TokenManager by executing data on the TokenManager side

More info in [PRD](https://www.notion.so/skalelabs/PRD-IMA-Execution-Manager-41090faeaf2349b4a7c605c882c05d2b)
[tasklist]
### Tasks
- [x] https://github.com/skalenetwork/IMA/issues/1745
- [x] https://github.com/skalenetwork/IMA/issues/1756
- [ ] Add errors handling
- [x] Add proper gas limitation
- [ ] Add upgrade script
- [ ] Add inline comments
